### ISSUE TITLE
ES: better error message when there's request error 

### ISSUE THREAD

**Issue by odanoburu** [own-pt/sensetion.el#110]

**Comment by odanoburu** [comment]
creating custom error messages when there's an error is difficult because of upstream bug https://github.com/tkf/emacs-request/issues/92. it seems to have been corrected but not yet released, so I'm waiting to see if there'll be a release soon.

if not, we can:

- use built-in emacs `url-retrieve`
  - :+1: is built-in, no setup involved (we might have problems with curl in windows)
  - :-1:  is slower
  - :-1: needs emacs 26+, because previous versions are buggy

- use https://github.com/skeeto/elfeed/blob/master/elfeed-curl.el
  - :+1: is fast, uses curl
  - :-1: might have trouble setting up in windows
  - :-1: is not a separate lib, so will bring in code that won't be used

**Comment by arademaker** [comment]
sorry, I am still not convinced we are talking about the same issue. I think we have errors in the HTTP/REQUEST level. But we also have errors in the application level. That is, if we sent a request and ES answer it with a JSON, this is not a protocol/communication error. But the JSON returned can contain a message saying that a document couldn't be updated: this is an application error.

**Comment by odanoburu** [comment]
yes, I thought so too, but apparently elasticsearch will return errors at the HTTP level when there's an error at the application level, see:

#### document not found
```
{
  "_index": "sensetion-docs",
  "_type": "_doc",
  "_id": "447909-a",
  "found": false
}
// GET http://localhost:9200/sensetion-docs/_doc/447909-a
// HTTP/1.1 404 Not Found
```

or

#### specified path does not exist

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "failed to create query: {\n  \"nested\" : {\n    \"query\" : {\n      \"term\" : {\n        \"tokens.lemmas\" : {\n          \"value\" : \"be%2\",\n          \"boost\" : 1.0\n        }\n      }\n    },\n    \"path\" : \"tokes\",\n    \"ignore_unmapped\" : false,\n    \"score_mode\" : \"avg\",\n    \"boost\" : 1.0\n  }\n}",
        "index_uuid": "MnHKskZdRDCAV19ZWH6upw",
        "index": "sensetion-docs"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "sensetion-docs",
        "node": "TbyR3a6PTPq7VxaHsny3pw",
        "reason": {
          "type": "query_shard_exception",
          "reason": "failed to create query: {\n  \"nested\" : {\n    \"query\" : {\n      \"term\" : {\n        \"tokens.lemmas\" : {\n          \"value\" : \"be%2\",\n          \"boost\" : 1.0\n        }\n      }\n    },\n    \"path\" : \"tokes\",\n    \"ignore_unmapped\" : false,\n    \"score_mode\" : \"avg\",\n    \"boost\" : 1.0\n  }\n}",
          "index_uuid": "MnHKskZdRDCAV19ZWH6upw",
          "index": "sensetion-docs",
          "caused_by": {
            "type": "illegal_state_exception",
            "reason": "[nested] failed to find nested object under path [tokes]"
          }
        }
      }
    ]
  },
  "status": 400
}
// GET http://localhost:9200/sensetion-docs/_search
// HTTP/1.1 400 Bad Request
// content-type: application/json; charset=UTF-8
// content-length: 1212
// Request duration: 0.037266s
```

we would have the situation you describe if it returned a HTTP 200, for example; or I misunderstood something? regardless, it certainly would be nice to read the output JSON and provide a better error message than a simple 404, but I can't seem to do it without a fix to the bug I mentioned.

**Comment by arademaker** [comment]
Hum, ES is not consistent!  This is an ES bug! 

The first case is an error because a document does not exist. The `INDEX/_doc/{id}` returns 404 when the document does not exist. The second case is an error in the query syntax, right?

**Comment by odanoburu** [comment]
> The second case is an error in the query syntax, right?

no, although it's an user error too, I specified a path that does not exist. a syntax error throws

```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unexpected close marker ']': expected '}' (for Object starting at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@27312311; line: 10, column: 17])\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@27312311; line: 15, column: 14]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unexpected close marker ']': expected '}' (for Object starting at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@27312311; line: 10, column: 17])\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@27312311; line: 15, column: 14]"
  },
  "status": 500
}
// GET http://localhost:9200/sensetion-synsets/_search
// HTTP/1.1 500 Internal Server Error
// content-type: application/json; charset=UTF-8
// content-length: 647
// Request duration: 0.023198s
```

**Comment by arademaker** [comment]
It looks like the right way to go is to start our own server-side wrapper to ES

**Comment by odanoburu** [comment]
stale
